---
settings:
  name: BlueXP Workload Factory for AWS
  platform: cloud
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Tutta la documentazione workload Factory
    url: "/index.html"
